import type { ExpoConfig } from 'expo/config';

/**
 * Bundle identifier — Apple uses this to permanently identify the app on
 * the App Store. Cannot be changed for a published app, so it's locked in
 * here. Override via EAS env vars only when intentionally building under a
 * different identity (e.g., a fork).
 */
const BUNDLE_ID = process.env.EXPO_BUNDLE_ID ?? 'com.spilsbury.zonnie';

/**
 * EAS owner — the Expo account that owns the EAS project. Set by `eas init`
 * on first run. Override via env var when intentionally building under a
 * different account.
 */
const EAS_OWNER = process.env.EXPO_OWNER ?? 'andy.spilsbury';

/**
 * EAS project ID — generated by `eas init`. Required for cloud builds and
 * OTA updates.
 */
const EAS_PROJECT_ID = process.env.EXPO_EAS_PROJECT_ID ?? '4f05324b-142b-48f5-ab7c-44a3c2d2c3ab';

const config: ExpoConfig = {
  name: 'Zonnie',
  // EAS slug is `andys` (auto-generated by `eas init`). Renaming the
  // display name on expo.dev doesn't change the slug — it's a separate
  // field. Slug is internal; doesn't appear on App Store / home screen.
  slug: 'andys',
  // 0.1.1 — bumped from 0.1.0 because we're disabling new architecture,
  // which is a native config change that requires a fresh build. The
  // runtimeVersion is bound to appVersion, so existing 0.1.0 OTAs won't
  // apply to this new install — that's intentional.
  version: '0.1.1',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'zonnie',
  userInterfaceStyle: 'automatic',
  // DISABLED — Andy's iOS crash log (2026-05-04) confirmed the time-range
  // crash was an `NSRangeException` in
  // `RCTLegacyViewManagerInteropComponentView.finalizeUpdates:`,
  // a known Fabric (new arch) bug with `react-native-maps`: the legacy
  // view-manager interop's subview index gets out of sync when many
  // markers' mount transactions land simultaneously (`insertObject:atIndex:
  // index 65 beyond bounds [0..63]`). Affects both image AND pinColor
  // markers since the bug is in the mounting layer, not in our marker
  // rendering. Disabling new arch routes through the old (Paper)
  // architecture which doesn't have this code path. Re-enable once
  // react-native-maps ships a Fabric-safe Marker component.
  newArchEnabled: false,
  // OTA updates: runtime is the app version. JS bundle changes within 0.1.0
  // ship as OTA; native changes (new packages, plugins) require a new build
  // and a new version. The `updates.url` points at the EAS Update server for
  // this project — required by `expo-updates` whenever it's installed, even
  // if we never push an update. Without it, prebuild errors out.
  runtimeVersion: { policy: 'appVersion' },
  updates: {
    url: `https://u.expo.dev/${EAS_PROJECT_ID}`,
  },
  ios: {
    supportsTablet: false,
    bundleIdentifier: BUNDLE_ID,
    // Privacy strings: even if the API is unused right now, including the
    // description prevents Apple from rejecting builds that LINK the framework.
    // `react-native-maps` links CoreLocation; we don't request location yet,
    // but the framework presence makes Apple expect this string to exist.
    infoPlist: {
      NSLocationWhenInUseUsageDescription:
        'Zonnie can show terraces near you on the map. Location is used only while the app is open and never sent off your device.',
      // Apple-required transport security: we only fetch from HTTPS endpoints.
      NSAppTransportSecurity: {
        NSAllowsArbitraryLoads: false,
      },
      // ITSAppUsesNonExemptEncryption=false skips an export-compliance form
      // on every TestFlight upload. Set true only if we add custom crypto.
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    package: BUNDLE_ID,
    adaptiveIcon: {
      backgroundColor: '#FFF8F0',
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    edgeToEdgeEnabled: true,
    predictiveBackGestureEnabled: false,
  },
  web: {
    output: 'static',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    'expo-router',
    'expo-font',
    [
      'expo-splash-screen',
      {
        image: './assets/images/splash-icon.png',
        imageWidth: 200,
        resizeMode: 'contain',
        backgroundColor: '#FFF8F0',
        dark: {
          backgroundColor: '#0F1729',
        },
      },
    ],
    [
      'expo-build-properties',
      {
        ios: {
          // 15.1 covers ~99% of iOS devices in 2026 and gives us modern APIs
          // (UIWindowScene, focus engine fixes, etc.) without dropping users.
          deploymentTarget: '15.1',
          // Belt-and-suspenders: top-level `newArchEnabled: false` should
          // be enough, but expo-build-properties takes precedence in
          // pod-install resolution. Setting it explicitly here too ensures
          // the Podfile is correctly generated for the old (Paper)
          // architecture path that avoids the react-native-maps Fabric
          // crash.
          newArchEnabled: false,
        },
        android: {
          newArchEnabled: false,
        },
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  ...(EAS_OWNER ? { owner: EAS_OWNER } : {}),
  extra: {
    ...(EAS_PROJECT_ID ? { eas: { projectId: EAS_PROJECT_ID } } : {}),
  },
};

export default config;
