import type { ExpoConfig } from 'expo/config';

/**
 * Bundle identifier — Apple uses this to permanently identify the app on
 * the App Store. Cannot be changed for a published app, so it's locked in
 * here. Override via EAS env vars only when intentionally building under a
 * different identity (e.g., a fork).
 */
const BUNDLE_ID = process.env.EXPO_BUNDLE_ID ?? 'com.spilsbury.zonnie';

/**
 * EAS owner — the Expo account that owns the EAS project. Set by `eas init`
 * on first run. Override via env var when intentionally building under a
 * different account.
 */
const EAS_OWNER = process.env.EXPO_OWNER ?? 'andy.spilsbury';

/**
 * EAS project ID — generated by `eas init`. Required for cloud builds and
 * OTA updates.
 */
const EAS_PROJECT_ID = process.env.EXPO_EAS_PROJECT_ID ?? '4f05324b-142b-48f5-ab7c-44a3c2d2c3ab';

/**
 * Apple Developer Team ID — required by `@bacons/apple-targets` to wire
 * the App Group entitlement onto both the main app and the widget
 * extension. Find it at developer.apple.com/account → Membership Details
 * (10-character alphanumeric, e.g. "AB12CD34EF").
 *
 * Not committed: set EXPO_APPLE_TEAM_ID locally and EAS Build picks it
 * up from the EAS secrets. Without it, prebuild prints a warning and
 * iOS builds may fail.
 */
const APPLE_TEAM_ID = process.env.EXPO_APPLE_TEAM_ID;

const config: ExpoConfig = {
  name: 'Zonnie',
  // EAS slug is `andys` (auto-generated by `eas init`). Renaming the
  // display name on expo.dev doesn't change the slug — it's a separate
  // field. Slug is internal; doesn't appear on App Store / home screen.
  slug: 'andys',
  // 1.0.0 = first App Store submission. Bumped from 0.1.0 (TestFlight
  // preview-only) on 2026-05-08 when prepping for review. Future
  // submissions follow semver: 1.0.x = patch (bug fix), 1.x.0 = minor
  // (additive feature), 2.0.0 = major (breaking UX change).
  // Bumped 1.1.0 → 1.2.0 alongside the runtime-policy revert below.
  // 1.1.0 builds (the App Store's build #7) will no longer match new
  // OTAs since the runtime version differs — same protection
  // `policy: 'fingerprint'` would have given us, achieved manually
  // by version bump. 1.1.0-runtime OTAs that fail-load on build #7
  // are already orphan; they won't accrue further.
  version: '1.2.0',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'zonnie',
  userInterfaceStyle: 'automatic',
  // KNOWN ISSUE: with `newArchEnabled: true`, the time-range crash
  // surfaces as an NSRangeException in
  // `RCTLegacyViewManagerInteropComponentView.finalizeUpdates:` when
  // many `react-native-maps` Markers' mount transactions land in one
  // tick. Crash log on file from 2026-05-04. The fix is one of:
  //   (a) upgrade `react-native-maps` to a version with proper Fabric
  //       support (1.20.1 uses legacy view manager interop on Fabric)
  //   (b) migrate to `expo-maps` (Expo's official replacement, native
  //       Fabric components)
  //   (c) disable new architecture here — but our 2026-05-04 attempts
  //       at this hit pod-install failures during EAS Build (no error
  //       detail), so leaving as-is until the proper fix lands.
  newArchEnabled: true,
  // OTA updates — discussion of the fix for build #7's OTA-orphan
  // problem (23.7 MB of failed-to-apply bundles).
  //
  // Original plan was `runtimeVersion: { policy: 'fingerprint' }` —
  // the canonical fix in 2026. Unfortunately the fingerprint policy
  // failed during the "Configure expo-updates" build phase on both
  // iOS and Android with EAS Build (UNKNOWN_ERROR). Likely a
  // conflict between fingerprint computation and our @bacons/apple-
  // targets widget plugin, or with the inline withGoogleMapsApiKey
  // plugin. Worth retrying in a future SDK; for now reverting to
  // policy: 'appVersion' which we know builds cleanly.
  //
  // To still solve the OTA-orphan problem, we BUMP the app version
  // 1.1.0 → 1.2.0 alongside this build. Result: build #7 (v1.1.0)
  // listens for runtime "1.1.0" OTAs; build #8 (v1.2.0) listens
  // for runtime "1.2.0". New OTAs published with current code go
  // out as "1.2.0", which build #7 will never see. Manual version
  // of fingerprint, same protection.
  //
  // requestHeaders.expo-channel-name is explicit, independent of
  // the policy choice. Same reasoning — defends against implicit
  // channel binding via eas.json drifting silently when deps change.
  runtimeVersion: { policy: 'appVersion' },
  updates: {
    url: `https://u.expo.dev/${EAS_PROJECT_ID}`,
    requestHeaders: {
      'expo-channel-name': 'production',
    },
  },
  ios: {
    supportsTablet: false,
    bundleIdentifier: BUNDLE_ID,
    ...(APPLE_TEAM_ID ? { appleTeamId: APPLE_TEAM_ID } : {}),
    // App Group entitlement — required for the home-screen widget
    // extension (in `targets/zonnie-widget/`) to read the snapshot
    // JSON the main app writes. The same identifier appears in:
    //   - targets/zonnie-widget/expo-target.config.js (entitlements)
    //   - targets/zonnie-widget/ZonnieWidget.entitlements
    //   - targets/zonnie-widget/ZonnieTimelineProvider.swift (groupId)
    //   - src/widget/snapshot.ts (WIDGET_APP_GROUP_ID)
    // All four MUST match character-for-character or the widget reads
    // an empty container.
    entitlements: {
      'com.apple.security.application-groups': ['group.com.spilsbury.zonnie'],
    },
    // Privacy strings: even if the API is unused right now, including the
    // description prevents Apple from rejecting builds that LINK the framework.
    // `react-native-maps` links CoreLocation; we don't request location yet,
    // but the framework presence makes Apple expect this string to exist.
    infoPlist: {
      NSLocationWhenInUseUsageDescription:
        'Zonnie centers the map on your location and surfaces nearby sunny terraces. Location is used only while the app is open and never sent off your device.',
      // Apple-required transport security: we only fetch from HTTPS endpoints.
      NSAppTransportSecurity: {
        NSAllowsArbitraryLoads: false,
      },
      // ITSAppUsesNonExemptEncryption=false skips the export-compliance
      // form on every TestFlight upload. This is the canonical Expo /
      // Apple way to declare no-non-exempt-encryption — it's already
      // sufficient on its own; there's no separate top-level
      // `infoPlistContainsExportCompliance` field on the Expo iOS
      // config schema (had been wrongly added here previously, caused
      // a tsc error).
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    package: BUNDLE_ID,
    adaptiveIcon: {
      backgroundColor: '#FFF8F0',
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    edgeToEdgeEnabled: true,
    predictiveBackGestureEnabled: false,
    // Google Maps API key for Android is injected via the
    // `./plugins/with-google-maps-api-key` config plugin (in the
    // plugins array below). We can't use the canonical
    // `android.config.googleMaps.apiKey` schema here because EAS Build
    // evaluates app.config.ts BEFORE injecting env vars — so reading
    // `process.env.GOOGLE_MAPS_ANDROID_API_KEY` at this scope resolves
    // to undefined, and Expo silently drops the meta-data tag. The
    // plugin reads the env var DURING the prebuild apply-mods phase,
    // by which point env vars are loaded.
  },
  web: {
    output: 'static',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    'expo-router',
    'expo-font',
    // Custom plugin that injects the Google Maps API key into
    // AndroidManifest.xml at prebuild time. See the plugin's own
    // file for why it's a separate module rather than inline.
    './plugins/with-google-maps-api-key',
    // Widget extension target. Reads `targets/zonnie-widget/expo-target.
    // config.js` to declare a WidgetKit extension during prebuild. The
    // Swift sources + Info.plist + entitlements in that directory are
    // copied into the generated Xcode project.
    '@bacons/apple-targets',
    [
      'expo-location',
      {
        locationAlwaysAndWhenInUsePermission:
          'Zonnie centers the map on your location and surfaces nearby sunny terraces.',
      },
    ],
    [
      'expo-splash-screen',
      {
        image: './assets/images/splash-icon.png',
        imageWidth: 200,
        resizeMode: 'contain',
        backgroundColor: '#FFF8F0',
        dark: {
          backgroundColor: '#0F1729',
        },
      },
    ],
    [
      'expo-build-properties',
      {
        ios: {
          // 15.1 covers ~99% of iOS devices in 2026 and gives us modern
          // APIs (UIWindowScene, focus engine fixes, etc.).
          deploymentTarget: '15.1',
        },
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  ...(EAS_OWNER ? { owner: EAS_OWNER } : {}),
  extra: {
    ...(EAS_PROJECT_ID ? { eas: { projectId: EAS_PROJECT_ID } } : {}),
  },
};

export default config;
