/**
 * Real Amsterdam building data for shadow ray-casting.
 *
 * Buildings are sourced from the Dutch 3D BAG dataset (https://3dbag.nl) —
 * centimetre-accurate heights and real footprints for every building within
 * 220m of a terrace. Generated by running:
 *
 *   python scripts/fetch-3dbag-buildings.py
 *
 * Falls back to procedurally generated buildings if buildings.json hasn't
 * been fetched yet, so the app still works out of the box.
 */

import type { Building } from '@/src/engines/types';
import { generateBuildingsForArea } from '@/src/engines/shadow';
import { AREA_CENTROIDS } from './areas';

// Populated by fetch-3dbag-buildings.py. Empty until that script is run.
let bag3dBuildings: Building[] | null = null;
try {
  // Dynamic require so the app doesn't crash if the file doesn't exist yet.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  bag3dBuildings = require('./buildings.json') as Building[];
} catch {
  // buildings.json not yet fetched — fall back to procedural generation below.
}

// ── Procedural fallback (used until buildings.json exists) ─────────────────

/** Lehmer (Park-Miller) LCG matching the original prototype's `rng()`. */
function makeRng(seed = 42): () => number {
  let s = seed;
  return () => {
    s = (s * 16807) % 2147483647;
    return (s - 1) / 2147483646;
  };
}

function generateFallbackBuildings(): Building[] {
  const rng = makeRng(42);
  const all: Building[] = [];
  for (const area of AREA_CENTROIDS) {
    all.push(...generateBuildingsForArea(area, rng));
  }
  return all;
}

// ── Public API ──────────────────────────────────────────────────────────────

let cached: Building[] | null = null;

/**
 * Returns the building set used by the shadow engine.
 *
 * Uses real 3D BAG data if buildings.json has been fetched; otherwise falls
 * back to the seeded procedural set so the app remains runnable.
 */
export function getBuildings(): Building[] {
  if (cached) return cached;
  const real = bag3dBuildings && bag3dBuildings.length > 0 ? bag3dBuildings : null;
  cached = real ?? generateFallbackBuildings();
  return cached;
}

/** Returns true if real 3D BAG data is loaded (vs the procedural fallback). */
export function isUsingRealBuildingData(): boolean {
  return bag3dBuildings !== null && bag3dBuildings.length > 0;
}

/** Test-only: reset the cache. */
export function _resetBuildingsCache(): void {
  cached = null;
}
